# To enable this aliases add the following line
# into your bash configuration file (~/.bashrc):
#
# source path-to-this-file
#  --or--
# . path-to-this-file

# Git shortcuts
alias gd='git diff'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gl='git log --oneline'

# Clean Python compiled files and swaps
alias clean='rm -f *.pyc *.swp'

# Go to working directory
alias cdw='cd ~/la'
